source "http://rubygems.org"

gem "cucumber", "3.0.2"
gem "mechanize", "2.7.5"
gem "json", "2.1.0"
gem "json_spec", "1.1.5"
gem "rack", "2.0.5"
gem "rake", "12.3.1"
gem "watir-webdriver", "0.9.9"
gem "selenium-webdriver", "3.12.0"
gem "methodize", "0.3.1"
gem "nokogiri", "1.8.2"


